# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1
if: branch = master OR tag IS present OR type = pull_request

notifications:
  email: false

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("EarCut")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
