language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
sudo: required
services:
  - docker

env:
  DOCKER_IMAGE: staticfloat/julia_crossbuild:x64

# Before anything else, get the latest versions of things
before_script:
  - docker pull $DOCKER_IMAGE
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia build_tarballs.jl
